name: Test

on: push

jobs:
  test-unity:
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE_FILE: ./tmp/ulf
    strategy:
      matrix:
        unityVersion:
        - 2020.1.13f1
        - 2019.4.14f1
        - 2019.3.12f1
        scriptBackend: ['mono']
        include:
        - unityVersion: 2020.1.13f1
          license: UNITY_LICENSE_2020_1_BASE64
        - unityVersion: 2019.4.14f1
          license: UNITY_LICENSE_2019_4_BASE64
        - unityVersion: 2019.3.12f1
          license: UNITY_LICENSE_2019_3_BASE64
    container:
      image: gableroux/unity3d:${{ matrix.unityVersion }}-linux-il2cpp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-UniTaskPubSub-${{ matrix.unityVersion }}
    - name: Dump unity license file
      shell: bash
      run: |
        mkdir ./tmp
        chmod 777 ./tmp
        echo -n "${{ secrets[matrix.license] }}" | base64 --decode > $UNITY_LICENSE_FILE
    - name: Load License
      shell: bash
      run: xvfb-run --error-file=/dev/stdout --auto-servernum --server-args='-screen 0 1024x768x24' /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile /dev/stdout -manualLicenseFile $UNITY_LICENSE_FILE || exit 0
    - name: Run Tests
      shell: bash
      run: xvfb-run --error-file=/dev/stdout --auto-servernum --server-args='-screen 0 1024x768x24' /opt/Unity/Editor/Unity -quit -batchmode -logFile /dev/stdout -projectPath ./ -runTests -testResults $GITHUB_WORKSPACE/tmp/TestResults.xml -testPlatform playmode -buildTarget StandaloneLinux64 -scriptbackend=${{ matrix.scriptBackend }} -nographics -silent-crashes
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: TestResults.xml
        path: ./tmp/TestResults.xml
