name: Test

on: push

jobs:
  test-unity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
        - 2020.3.0f1
        - 2019.4.22f1
        - 2019.3.15f1
        include:
        - unityVersion: 2020.3.0f1
          license: UNITY_LICENSE_2020_3
        - unityVersion: 2019.4.22f1
          license: UNITY_LICENSE_2019_4
        - unityVersion: 2019.3.15f1
          license: UNITY_LICENSE_2019_3
        # - unityVersion: 2018.4.32f1
        #   license: UNITY_LICENSE_2018_4
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-UniTaskPubSub-${{ matrix.unityVersion }}
        restore-keys: |
          Library-UniTaskPubSub
          Library-
    - uses: game-ci/unity-test-runner@v2.0-alpha-2
      env:
        UNITY_LICENSE: ${{ secrets[matrix.license] }}
      with:
        projectPath: .
        unityVersion: ${{ matrix.unityVersion }}
        # customParameters: -testSettingsFile ./testSettings.json
    - uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: artifacts
